/**
 * ASTRA Part 3 Enums: Centre Network, 7-Day Smart Booking & Multi-Department Operations
 */

export enum CentreVerificationStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE',
}

export enum CentreOperationalStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  TEMPORARILY_UNAVAILABLE = 'TEMPORARILY_UNAVAILABLE',
  MAINTENANCE = 'MAINTENANCE',
}

export enum CounterStatus {
  AVAILABLE = 'AVAILABLE',
  BUSY = 'BUSY',
  OFFLINE = 'OFFLINE',
  MAINTENANCE = 'MAINTENANCE',
}

export enum BookingSession {
  MORNING = 'MORNING',
  AFTERNOON = 'AFTERNOON',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  BOOKED = 'BOOKED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  CHECKED_IN = 'CHECKED_IN',
  WEIGHMENT = 'WEIGHMENT',
  QUALITY_ASSESSMENT = 'QUALITY_ASSESSMENT',
  PROCUREMENT = 'PROCUREMENT',
  PAYMENT = 'PAYMENT',
  COMPLETED = 'COMPLETED',
}

export enum WeighmentStatus {
  WAITING = 'WAITING',
  DEVICE_CONNECTED = 'DEVICE_CONNECTED',
  READING_RECEIVED = 'READING_RECEIVED',
  RECORDED = 'RECORDED',
  CORRECTION_PENDING = 'CORRECTION_PENDING',
  CORRECTION_APPROVED = 'CORRECTION_APPROVED',
  CORRECTION_REJECTED = 'CORRECTION_REJECTED',
}

export enum QualityGrade {
  GRADE_A = 'GRADE_A',
  GRADE_B = 'GRADE_B',
  GRADE_C = 'GRADE_C',
  REJECTED = 'REJECTED',
}

export enum ProcurementDecision {
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  PARTIAL_ACCEPTED = 'PARTIAL_ACCEPTED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SETTLED = 'SETTLED',
  FAILED = 'FAILED',
}
